# Generated by Django 2.0.7 on 2018-07-21 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='email',
            field=models.CharField(default='alex', max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='test',
            field=models.EmailField(max_length=19, null=True),
        ),
    ]
